In [1]:
# example loading simulation file called filename

slice1 = np.load('filename')['arr_0']
test = np.loadl('filename')
test.key

slice2 = np.load('filename2')['arr_0']
slice3 = np.load('filename3')['arr_0']
sliceT = np.log10(10**slice1+10**slice2+10**slice3)

# then bin the pixels in each dimension by a factor of 40 (to get rid of weird high or low pixels that aren't physical)
# (down to 800 cubed pixels)

imshow

NameError: name 'np' is not defined

In [1]:
import numpy as np

In [2]:
def indices_region(xbox,ybox):
# Create 2d arrays for both x and y indices values to pick out the data in the regions 
#(not sure, there's probably a better way to do this...)

#[53,53,56,56,53],[9.2,10,8.5,7.7,9.2]
#xbox = [53, 53, 56,56] # lower left, upper left, upper right, lower right
#ybox = [9.2,10,8.5,7.7] # lower left, upper left, upper right, lower right

#    xbox = [1,10,10,1] # lower left, upper left, upper right, lower right
#    ybox = [20,15,25,30]

#xacross_length = np.abs(xbox[2] - xbox[1])  
#xdown_length = np.abs(xbox[1]-xbox[0])       
#yacross_length = np.abs(ybox[2] - ybox[1])  
#ydown_length = np.abs(ybox[1]-ybox[0])         
    xacross_length = (xbox[2] - xbox[1])  
    xdown_length = (xbox[1]-xbox[0])       
    yacross_length = (ybox[2] - ybox[1])  
    ydown_length = (ybox[1]-ybox[0])   
    print('xacross_length,yacross_length,xdown_length,ydown_length:  '+str(xacross_length)+', '+
          str(yacross_length)+', '+str(xdown_length)+', '+str(ydown_length))

  #  xacross_length = max(xbox)-min(xbox)
  #  yacross_length = max(ybox)-min(ybox)
#
#    print('xacross_length,yacross_length,xdown_length,ydown_length:  '+str(xacross_length)+', '+
#          str(yacross_length)+', '+str(xdown_length)+', '+str(ydown_length))
    
    
    if xacross_length > yacross_length:
        iterable = np.round(np.arange(xacross_length+1)*float(yacross_length)/float(xacross_length))
        yacross = [ybox[1]+y for y in iterable.astype(int)]
        xacross = [xbox[1]+x for x in xrange(xacross_length+1)]
        print('xacross_length > yacross_length:')
        print('iterable: '+str(iterable))
    elif xacross_length < yacross_length:
        iterable = np.round(np.arange(yacross_length+1)*float(xacross_length)/float(yacross_length))
        xacross = [xbox[1]+x for x in iterable.astype(int)]
        yacross = [ybox[1]+y for y in xrange(yacross_length+1)]
        print('xacross_length < yacross_length:')
        print('iterable: '+str(iterable))
    else:
        xacross = [xbox[1]+x for x in xrange(xacross_length+1)]
        yacross = [ybox[1]+y for y in xrange(yacross_length+1)]
        print('xacross_length = yacross_length')

    if xdown_length > ydown_length:
        iterable = np.round(np.arange(xdown_length+1)*float(ydown_length)/float(xdown_length))
        yfull = [np.array(yacross)-y for y in iterable.astype(int)]    
        xfull = [np.array(xacross)-x for x in xrange(xdown_length+1)]
        print('xdown_length > ydown_length:')
        print('iterable: '+str(iterable))    
    elif xdown_length < ydown_length:
        iterable = np.round(np.arange(ydown_length+1)*float(xdown_length)/float(ydown_length))
        xfull = [np.array(xacross)-x for x in iterable.astype(int)]
        yfull = [np.array(yacross)-y for y in xrange(ydown_length+1)]
        print('xdown_length < ydown_length:')
        print('iterable: '+str(iterable))    
    else:
        xfull = [np.array(xacross)-x for x in xrange(xdown_length+1)]
        yfull = [np.array(yacross)-y for y in xrange(ydown_length+1)]
        print('xdown_length = ydown_length:')

    xfull = np.array(xfull)
    yfull = np.array(yfull)
    
    return xfull, yfull

In [28]:
#xbox = [1,10,10,1] # lower left, upper left, upper right, lower right
#ybox = [20,15,25,30]
#xbox = np.array([53,53,56,56])*3200./100.
#ybox = np.array([9.2,10,8.5,7.7])*3200./100.
xbox = np.array([47.2,46.2,47.2,48.2])*3200./100.
ybox = np.array([10,14,14,10])*3200./100.
#xbox = np.array([43,43,46,46])*3200./100.
#ybox = np.array([7.5,8.2,7.2,6.5])*3200./100.
print(xbox,ybox)
#print(xbox.astype(int),ybox.astype(int))
xfull, yfull= indices_region(xbox.astype(int),ybox.astype(int))  
#xfull, yfull= indices_region(xbox,ybox)  
xfull#*100./3200.

(array([ 1510.4,  1478.4,  1510.4,  1542.4]), array([ 320.,  448.,  448.,  320.]))
xacross_length,yacross_length,xdown_length,ydown_length:  32, 0, -32, 128
xacross_length > yacross_length:
iterable: [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
xdown_length < ydown_length:
iterable: [ -0.  -0.  -0.  -1.  -1.  -1.  -2.  -2.  -2.  -2.  -2.  -3.  -3.  -3.  -4.
  -4.  -4.  -4.  -4.  -5.  -5.  -5.  -6.  -6.  -6.  -6.  -6.  -7.  -7.  -7.
  -8.  -8.  -8.  -8.  -8.  -9.  -9.  -9. -10. -10. -10. -10. -10. -11. -11.
 -11. -12. -12. -12. -12. -12. -13. -13. -13. -14. -14. -14. -14. -14. -15.
 -15. -15. -16. -16. -16. -16. -16. -17. -17. -17. -18. -18. -18. -18. -18.
 -19. -19. -19. -20. -20. -20. -20. -20. -21. -21. -21. -22. -22. -22. -22.
 -22. -23. -23. -23. -24. -24. -24. -24. -24. -25. -25. -25. -26. -26. -26.
 -26. -26. -27. -27. -27. -28. -28. -28. -28. -28. -29. -29. -29. -30. -30.
 -30. -30. -30. -3

array([[1478, 1479, 1480, ..., 1508, 1509, 1510],
       [1478, 1479, 1480, ..., 1508, 1509, 1510],
       [1478, 1479, 1480, ..., 1508, 1509, 1510],
       ..., 
       [1510, 1511, 1512, ..., 1540, 1541, 1542],
       [1510, 1511, 1512, ..., 1540, 1541, 1542],
       [1510, 1511, 1512, ..., 1540, 1541, 1542]])

In [4]:
yfull#*100./3200.

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
       [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [22]:
datafull = np.zeros(yfull.shape)

range(yfull.shape[1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [26]:
for i in range(yfull.shape[0]):
    for j in range(yfull.shape[1]):
        datafull[i,j] = yfull[i,j]
        
print(datafull)
print(np.mean(datafull))

[[ 15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.]
 [ 16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.]
 [ 16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.]
 [ 17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.]
 [ 17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.]
 [ 18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.]
 [ 18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.]
 [ 19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.]
 [ 19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.]
 [ 20.  21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]]
22.5


In [5]:
x = [[(i+j) for i in range(50)] for j in range(50)]
x = np.array(x)
print(x)

[[ 0  1  2 ..., 47 48 49]
 [ 1  2  3 ..., 48 49 50]
 [ 2  3  4 ..., 49 50 51]
 ..., 
 [47 48 49 ..., 94 95 96]
 [48 49 50 ..., 95 96 97]
 [49 50 51 ..., 96 97 98]]


In [126]:
# Cycle through the arrays, spitting out the indices that we want to sum up over.

for x,y in zip(xfull,yfull):
    for i,j in zip(x,y):
        print i,j

10 15
10 16
10 17
10 18
10 19
10 20
10 21
10 22
10 23
10 24
10 25
9 16
9 17
9 18
9 19
9 20
9 21
9 22
9 23
9 24
9 25
9 26
8 16
8 17
8 18
8 19
8 20
8 21
8 22
8 23
8 24
8 25
8 26
7 17
7 18
7 19
7 20
7 21
7 22
7 23
7 24
7 25
7 26
7 27
6 17
6 18
6 19
6 20
6 21
6 22
6 23
6 24
6 25
6 26
6 27
5 18
5 19
5 20
5 21
5 22
5 23
5 24
5 25
5 26
5 27
5 28
4 18
4 19
4 20
4 21
4 22
4 23
4 24
4 25
4 26
4 27
4 28
3 19
3 20
3 21
3 22
3 23
3 24
3 25
3 26
3 27
3 28
3 29
2 19
2 20
2 21
2 22
2 23
2 24
2 25
2 26
2 27
2 28
2 29
1 20
1 21
1 22
1 23
1 24
1 25
1 26
1 27
1 28
1 29
1 30


In [111]:
yfull[0,0]

15

In [114]:
x[xfull[0,0],yfull[0,0]]

25

In [134]:
dists = np.squeeze(np.vstack(([xfull.T], [yfull.T])).T)
#dists
for x in dists:
    print x

[[10 15]
 [10 16]
 [10 17]
 [10 18]
 [10 19]
 [10 20]
 [10 21]
 [10 22]
 [10 23]
 [10 24]
 [10 25]]
[[ 9 16]
 [ 9 17]
 [ 9 18]
 [ 9 19]
 [ 9 20]
 [ 9 21]
 [ 9 22]
 [ 9 23]
 [ 9 24]
 [ 9 25]
 [ 9 26]]
[[ 8 16]
 [ 8 17]
 [ 8 18]
 [ 8 19]
 [ 8 20]
 [ 8 21]
 [ 8 22]
 [ 8 23]
 [ 8 24]
 [ 8 25]
 [ 8 26]]
[[ 7 17]
 [ 7 18]
 [ 7 19]
 [ 7 20]
 [ 7 21]
 [ 7 22]
 [ 7 23]
 [ 7 24]
 [ 7 25]
 [ 7 26]
 [ 7 27]]
[[ 6 17]
 [ 6 18]
 [ 6 19]
 [ 6 20]
 [ 6 21]
 [ 6 22]
 [ 6 23]
 [ 6 24]
 [ 6 25]
 [ 6 26]
 [ 6 27]]
[[ 5 18]
 [ 5 19]
 [ 5 20]
 [ 5 21]
 [ 5 22]
 [ 5 23]
 [ 5 24]
 [ 5 25]
 [ 5 26]
 [ 5 27]
 [ 5 28]]
[[ 4 18]
 [ 4 19]
 [ 4 20]
 [ 4 21]
 [ 4 22]
 [ 4 23]
 [ 4 24]
 [ 4 25]
 [ 4 26]
 [ 4 27]
 [ 4 28]]
[[ 3 19]
 [ 3 20]
 [ 3 21]
 [ 3 22]
 [ 3 23]
 [ 3 24]
 [ 3 25]
 [ 3 26]
 [ 3 27]
 [ 3 28]
 [ 3 29]]
[[ 2 19]
 [ 2 20]
 [ 2 21]
 [ 2 22]
 [ 2 23]
 [ 2 24]
 [ 2 25]
 [ 2 26]
 [ 2 27]
 [ 2 28]
 [ 2 29]]
[[ 1 20]
 [ 1 21]
 [ 1 22]
 [ 1 23]
 [ 1 24]
 [ 1 25]
 [ 1 26]
 [ 1 27]
 [ 1 28]
 [ 1 29]
 [ 1 30]]
